# Site settings
title: H. K. Ilter
email: info@hkilter.com
description: > # this means to ignore newlines until "baseurl:"
  This website is about one of my projects, SCOM - Ontological Supply
  Chain Management Model) which aims to create a dynamic model for
  tracking and tracing product/service, members, flow and operations
  of a supply chain with an upper ontology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hkilter
github_username:  hkilter

# Build settings
markdown: kramdown
