# Site settings
title: SCOM
email: 
description: > # this means to ignore newlines until "baseurl:"
  SCOM - Ontological Supply Chain Management Model aims to create
  a dynamic model for tracking and tracing elements of a supply chain.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hkilter.com" # the base hostname & protocol for your site
twitter_username: hkilter
github_username:  

# Build settings
markdown: kramdown
